// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1e5ms-bbw16jmaT6gcEt1dgJ8IgWp_9s',
    appId: '1:101146301709:android:32ea9ec3f6fb0f6edb0c44',
    messagingSenderId: '101146301709',
    projectId: 'captain-3ef2d',
    storageBucket: 'captain-3ef2d.appspot.com',
  );

//

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBO72ubgFij1x-7GT3Xvje47g-us8VY74Q',
    appId: '1:101146301709:ios:955b23f0114bec4edb0c44',
    messagingSenderId: '101146301709',
    projectId: 'captain-3ef2d',
    storageBucket: 'captain-3ef2d.appspot.com',
    iosBundleId: 'com.onlypass.captian.untitled7',
  );

//
}
