// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: 'AIzaSyDXq7PseZp_Mzrqcb9R4VDsv4v323YUhEs',
//     appId: '1:895178447738:android:274a144d7f92f43a53d4c3',
//     messagingSenderId: '895178447738',
//     projectId: 'onlypass-captain-40e0b',
//     databaseURL: 'https://onlypass-captain-40e0b-default-rtdb.firebaseio.com',
//     storageBucket: 'onlypass-captain-40e0b.appspot.com',
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: 'AIzaSyCrGSlmpXgMGfKo4d76eOsriSWwC0hG4Qw',
//     appId: '1:895178447738:ios:c3b48a209afc8ce053d4c3',
//     messagingSenderId: '895178447738',
//     projectId: 'onlypass-captain-40e0b',
//     databaseURL: 'https://onlypass-captain-40e0b-default-rtdb.firebaseio.com',
//     storageBucket: 'onlypass-captain-40e0b.appspot.com',
//     iosBundleId: 'com.onlypass.captian.untitled7',
//   );
// }
